// vue/vue_test/38_src_缓存路由组件/pages/Detail_.vue
<template>
  <ul>
    <li>消息编号：{{ id }}</li>
    <li>消息标题：{{ title }}</li>
  </ul>
</template>

<script>
export default {
  name:'Detail_',
  props:['id', 'title'],
 computed: {
    // id(){
    // 	return this.$route.query.id
    // },
    // title(){
    // 	return this.$route.query.title
    // },
  },
  mounted() {
    // console.log(this.$route)
  },
}
</script>

<style>

</style>

// react/hello/06_src_路由的params参数/pages/Detail.jsx
import React from 'react'
import {useParams,useMatch} from 'react-router-dom'
export default function Detail() {
  const{id,title,content}=useParams()
  // const x=useMatch('/home/message/detail/:id/:title/:content')
  // console.log(x)
  return (
    <ul>
      <li>消息编号：{id}</li>
      <li>消息标题：{title}</li>
      <li>消息内容：{content}</li>
    </ul>
  )
}
