// react/hello/06_src_路由的params参数/pages/Home.jsx
import React from 'react'
import {NavLink,Outlet} from 'react-router-dom'

export default function Home() {
  return (
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className="nav nav-tabs">
            <li>
              <NavLink className="list-group-item" to="news">News</NavLink>
            </li>
            <li>
              <NavLink className="list-group-item" to="message">Message</NavLink>
            </li>
          </ul>
          {/* 指定路由组件呈现的位置 */}
          <Outlet/>
        </div>
      </div>
  )
}

// vue/vue_test/34_src_路由的params参数/pages/Home_.vue
<template>
  <div>
  <h2>Home组件内容</h2>
  <div>
    <ul class="nav nav-tabs">
      <li>
        <router-link class="list-group-item" active-class="active" to="/home/news">News</router-link>
      </li>
      <li>
        <router-link class="list-group-item" active-class="active" to="/home/message">Message</router-link>
      </li>
    </ul>
   <router-view></router-view>
  </div>
</div>
</template>

<script>
  export default {
    name:'Home_'
  }
</script>

<style>

</style>
