// react/react_staging/11_src_Switch的使用/App.jsx
import React, { Component } from 'react'
import {Route,Switch} from 'react-router-dom'
import Home from './pages/Home' //Home是路由组件
import About from './pages/About' //About是路由组件
import Header from './components/Header' //Header是一般组件
import MyNavLink from './components/MyNavLink'
import Test from './pages/Test'

export default class App extends Component {
	render() {
		return (
			<div>
				<div className="row">
					<div className="col-xs-offset-2 col-xs-8">
						<Header/>
					</div>
				</div>
				<div className="row">
					<div className="col-xs-2 col-xs-offset-2">
						<div className="list-group">

							{/* 原生html中，靠<a>跳转不同的页面 */}
							{/* <a className="list-group-item" href="./about.html">About</a>
							<a className="list-group-item active" href="./home.html">Home</a> */}

							{/* 在React中靠路由链接实现切换组件--编写路由链接 */}
              <MyNavLink to="/about" a={1} b={2} c={3} >About</MyNavLink>
              <MyNavLink to="/home" >Home</MyNavLink>
            </div>
					</div>
					<div className="col-xs-6">
						<div className="panel">
							<div className="panel-body">
								{/* 注册路由 */}
                <Switch>
                  <Route path="/about" component={About}/>
								  <Route path="/home" component={Home}/>
								  <Route path="/home" component={Test}/>
                </Switch>
							</div>
						</div>
					</div>
				</div>
			</div>
		)
	}
}

// vue/vue_test/31_src_多级路由/App.vue
<template>
  <div>
    <div class="row">
      <Banner_/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 原始html中我们使用a标签实现页面的跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->          
          <!-- Vue中借助router-link标签实现路由的切换 -->
          <router-link class="list-group-item" active-class="active" to="/about_">About</router-link> 
          <router-link class="list-group-item" active-class="active" to="/home_">Home</router-link>

        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 指定组件的呈现位置 -->
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

import Banner_ from './components/Banner_'
export default {
  name:'App',
  components:{Banner_}
}
</script>
