// react/react_staging/07_src_github搜索案例_fetch/components/Search/index.jsx
import React, { Component } from 'react'
import PubSub from 'pubsub-js'
// import axios from 'axios'
export default class Search extends Component {

  search= async()=>{
    // 获取用户的输入（连续解构赋值+重命名）
    const {keyWordElement:{value:keyWord}}=this
    // 发送请求前通知List更新状态
    PubSub.publish('atguigu',{isFirst:false,isLoading:true})
    //#region 发送网络请求---使用axios发送
    /* axios.get(`/api1/search/users2?q=${keyWord}`).then(
      response=>{
        // 请求成功后通知List更新状态
        PubSub.publish('atguigu',{isLoading:false,users:response.data.items})
      },
      error=>{
        // 请求失败后通知List更新状态
        PubSub.publish('atguigu',{isLoading:false,err:error.message})
      }
    ) */
    // #endregion
  
    // 发送网络请求---使用fetch发送(未优化)
   /* fetch(`/api1/search/users2?q=${keyWord}`).then(
      response=>{console.log('联系服务器成功了')
      return response.json()
    },
      error=>{
        console.log('联系服务器失败了',error)
        return new Promise(()=>{})
      }
   ).then(
      response=>{console.log('获取数据成功了',response)},
      error=>{console.log('获取数据失败了',error)}
    ) */

    // 发送网络请求---使用fetch发送(优化)
    try {
      const response = await fetch(`/api1/search/users2?q=${keyWord}`)
      const data=await response.json()
      PubSub.publish('atguigu',{isLoading:false,users:data.items})
    } catch (error) {
      console.log('请求出错',error)
        PubSub.publish('atguigu',{isLoading:false,err:error.message})
    }
  }
  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">搜索github用户</h3>
        <div>
          <input ref={c=>this.keyWordElement=c} type="text" placeholder="输入关键字点击搜索"/>&nbsp;
          <button onClick={this.search}>搜索</button>
        </div>
      </section>
    )
  }
}

// vue/vue_test/20_src_guthub_搜索案例/components/Search_.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input type="text" placeholder="enter the name you search" v-model="keyWord"/>&nbsp;<button @click="searchUsers">Search</button>
    </div>
  </section>
</template>

<script>
import axios from 'axios'
export default {
  name:'Search_',
  data() {
    return {
      keyWord: ''
    }
  },
  methods: {
    searchUsers() {
      //请求前更新List的数据
      this.$bus.$emit('updateListData', { isLoading: true, errMsg: '', users: [], isFirst: false })
      axios.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
        response => {
          //请求成功后更新List的数据
          this.$bus.$emit('updateListData', { isLoading: false, errMsg: '', users: response.data.items })
        },
        error => {
          //请求后更新List的数据
          this.$bus.$emit('updateListData', { isLoading: false, errMsg: error.message, users: [] })
        }
      )
    }
  },
}
</script>
