// vue/vue_test/21_src_github搜索案例_vue-resource/components/Search_.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input type="text" placeholder="enter the name you search" v-model="keyWord"/>&nbsp;<button @click="searchUsers">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  name:'Search_',
  data() {
    return {
      keyWord: ''
    }
  },
  methods: {
    searchUsers() {
      //请求前更新List的数据
      this.$bus.$emit('updateListData', { isLoading: true, errMsg: '', users: [], isFirst: false })
      this.$http.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
        response => {
          //请求成功后更新List的数据
          this.$bus.$emit('updateListData', { isLoading: false, errMsg: '', users: response.data.items })
        },
        error => {
          //请求后更新List的数据
          this.$bus.$emit('updateListData', { isLoading: false, errMsg: error.message, users: [] })
        }
      )
    }
  },
}
</script>

// react/react_staging/06_src_github搜索案例_pubsub/components/Search/index.jsx
import React, { Component } from 'react'
import PubSub from 'pubsub-js'
import axios from 'axios'
export default class Search extends Component {

  search=()=>{
    // 获取用户的输入（连续解构赋值+重命名）
    const {keyWordElement:{value:keyWord}}=this
    // 发送请求前通知List更新状态
    PubSub.publish('atguigu',{isFirst:false,isLoading:true})
    // 发送网络请求
    axios.get(`/api1/search/users?q=${keyWord}`).then(
      response=>{
        // 请求成功后通知List更新状态
        PubSub.publish('atguigu',{isLoading:false,users:response.data.items})
      },
      error=>{
        // 请求失败后通知List更新状态
        PubSub.publish('atguigu',{isLoading:false,err:error.message})
      }
    )
  }
  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">搜索github用户</h3>
        <div>
          <input ref={c=>this.keyWordElement=c} type="text" placeholder="输入关键字点击搜索"/>&nbsp;
          <button onClick={this.search}>搜索</button>
        </div>
      </section>
    )
  }
}
